version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  front:
    image: wendy-front
    container_name: front
    ports:
      - '80:80'
    depends_on:
      - api

  api:
    build: .
    container_name: api
    env_file:
      - .env
    ports:
      - '3000:3000'
    command: npm run build && npm run api
    tty: true
    depends_on:
      - postgres

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    command: npm run build && npm run bot
    tty: true
    depends_on:
      - postgres


  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '127.0.0.1:8080:8080'
